Skip to content
This repository
Search
Pull requests
Issues
Marketplace
Explore
 @GRamirez2
Sign out
1
0 0 GRamirez2/11-11studios
 Code  Issues 0  Pull requests 0  Projects 0  Wiki  Insights  Settings
11-11studios/_config.yml
9f2b4bf  4 hours ago
@GRamirez2 GRamirez2 removed url from config
     
44 lines (40 sloc)  1.78 KB
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 11-11 Studios Blog
email: admin@tech-mex.io
description: >- # this means to ignore newlines until "baseurl:"
  The 11-11Studios BLOG is where I our clients up to date with out current options for their sites. As we develop new features and integrate them into our CMS we will feature them here with a description and instructions on how to use our new products. 
  This text will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /11-11studios # the subpath of your site, e.g. /blog
url: https://gramirez2.github.io/11-11studios/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _georgeramirez_
github_username:  GRamirez2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
© 2018 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
API
Training
Shop
Blog
About